name: Build
on:
  push:
    - main
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install package
        run: npm install && mkdir -p ./bin

      - name: Build package
        run: npm run package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: theme-dracula-gray
          path: ./bin/dracula-gray.vsix
